In [2]:
#import libraries
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print("\nAverage number", arr.mean())

[10 20 30 40 50]

Average number 30.0


In [6]:
#indexing
print(arr[3])
print(arr[-1])


40
50


In [9]:
#slicing
print(arr[1:4])
print(arr[::2])
print(arr[:7])
print(arr[-1:-4])
print(arr[:])

[20 30 40]
[10 30 50]
[10 20 30 40 50]
[]
[10 20 30 40 50]


In [13]:
#2D indexing
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[0, 1])
print(matrix[:, 1])
print(matrix[1, :])
print(matrix[2, 0:2])

2
[2 5 8]
[4 5 6]
[7 8]


In [18]:
#changing 1D array to 2D array
arr2 = np.arange(1, 13)
reshape = arr2.reshape(2, 6)

print("Original array:", arr2)
print("Reshaped array:", reshape)

#flatten to 1d array
flatten = reshape.flatten()
print("Flatten:", flatten)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
#working with mathematical operation on array
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([10, 20, 30, 40, 50])

#basic math operators
print(arr3 + arr4)
print(arr3 - arr4)
print(arr3 * arr4)
print(arr3 / arr4)

#scaler operator
print("Scelar operator\n")
print(arr4**2)
print(arr4 / 2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
Scelar operator

[ 100  400  900 1600 2500]
[ 5. 10. 15. 20. 25.]


In [24]:
#working with matrix element using (dot product)
matrix_1 = np.array([
    [1, 2],
    [3, 4]
])

matrix_2 = np.array([
    [5, 6],
    [7, 8]
])

dot = np.dot(matrix_1, matrix_2)
print(dot)

multiply = matrix_1 * matrix_2
print(multiply)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
